{
 "title": "Demo",
 "time": { "from": "2024-11-13T22:09:31.608Z", "to": "2024-11-13T22:24:39.371Z" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,http_route)"
    }
   },
   {
    "name": "status_code",
    "label": "status_code",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,http_response_status_code)"
    }
   },
   {
    "name": "http_method",
    "label": "http_method",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,http_request_method)"
    }
   },
   { "name": "percentile", "label": "percentile", "query": "0.5,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  { "title": "HTTP metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(http_response_status_code) (increase(http_server_request_duration_seconds_count{http_response_status_code=~\"$status_code\", http_request_method=~\"GET\", http_route=~\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{http_route=~\"$endpoint\", http_request_method=~\"$http_method\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 5xx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{http_route=~\"$endpoint\", http_response_status_code=~\"5..\", http_request_method=~\"$http_method\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 4xx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{http_route=~\"$endpoint\", http_response_status_code=~\"4..\", http_request_method=~\"$http_method\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response Time Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_request_duration_seconds_bucket{http_route=~\"$endpoint\", http_request_method=~\"$http_method\", http_response_status_code=~\"$status_code\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, http_route, http_request_method) (rate(http_server_request_duration_seconds_bucket[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WeatherApp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Forecast Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, http_route, http_request_method) (rate(weather_forecast_duration_seconds_bucket[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Recorded Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_current_temperature{otel_scope_name=\"WeatherApp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Forecasts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(weather_forecast_requests_total{otel_scope_name=\"WeatherApp\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}